# Generated by Django 3.0.2 on 2022-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider/')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
