# Generated by Django 3.0.2 on 2022-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220328_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='about',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
